workflows:
  android-build:
    name: Android Build
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Go to project folder
        script: |
          cd voice_ai_health_assistant

      - name: Create Flutter structure
        script: |
          flutter create .

      - name: Fix dependencies
        script: |
          flutter pub upgrade

      - name: Clean build
        script: |
          flutter clean

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - voice_ai_health_assistant/build/app/outputs/flutter-apk/*.apk
